version: "3.8"

services:
  api:
    build: .
    container_name: pricepulse-api-dev-11
    ports:
      - "9000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - WORKER_COUNT=6
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - BIGQUERY_DATASET_ID=${BIGQUERY_DATASET_ID}
      - DATA_SOURCE=${DATA_SOURCE}
      - REDIS_URL=redis://redis:6379/0
      - RELOAD_FLAG=--reload
    volumes:
      - ./app:/app/app
      - ./gcp-credentials.json:/app/gcp-credentials.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 15s

  # Redis for caching analytical query results
  redis:
    image: redis:alpine
    container_name: pricepulse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 20s
      retries: 5
volumes:
  redis-data:
