name: CI - Build and Push Docker Image

# Trigger workflow on push to main
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Set environment variables for cleaner references
    env:
      DOCKER_USER: ${{ vars.DOCKERHUB_USERNAME }} # Organization variable
      DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }} # Organization secret
      IMAGE_NAME: backend-api
      IMAGE_TAG: latest

    steps:
      # Step 1: Checkout code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      # Step 3: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
